"""Adicionando tabela cores_disponiveis

Revision ID: 22f8175dd0da
Revises: c892c37c1665
Create Date: 2025-05-27 17:24:36.737563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22f8175dd0da'
down_revision = 'c892c37c1665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cores_disponiveis', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_column('cores_disponiveis')

    # ### end Alembic commands ###
