"""Adiciona campo colecao_id ao Produto

Revision ID: 393d4f95c726
Revises: 8841b895c05f
Create Date: 2025-06-11 19:57:27.121324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '393d4f95c726'
down_revision = '8841b895c05f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('colecoes', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('imagem',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('colecao_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_produto_colecao_id',  # nome da constraint
            'colecoes',
            ['colecao_id'],
            ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('colecao_id')

    with op.batch_alter_table('colecoes', schema=None) as batch_op:
        batch_op.alter_column('imagem',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    op.create_table('produto_colecao',
    sa.Column('produto_id', sa.INTEGER(), nullable=True),
    sa.Column('colecao_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['colecao_id'], ['colecoes.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], )
    )
    # ### end Alembic commands ###
