"""Adicionando tabela em Produtos de destaque

Revision ID: 39c8c7514496
Revises: 5a6126d4e088
Create Date: 2025-05-29 20:37:31.919710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39c8c7514496'
down_revision = '5a6126d4e088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destaque', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_column('destaque')

    # ### end Alembic commands ###
