"""adiciona campo cor ao ItemPedido

Revision ID: 4b455ee67653
Revises: 22f8175dd0da
Create Date: 2025-05-27 18:19:23.715670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b455ee67653'
down_revision = '22f8175dd0da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itens_pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cor', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itens_pedido', schema=None) as batch_op:
        batch_op.drop_column('cor')

    # ### end Alembic commands ###
