"""Adiciona campo colecao_2025 ao Produto

Revision ID: 511255eb93ca
Revises: aa75bd1e34c2
Create Date: 2025-06-10 21:08:49.408119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '511255eb93ca'
down_revision = 'aa75bd1e34c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('colecao_2025', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_column('colecao_2025')

    # ### end Alembic commands ###
