"""create produto_colecao

Revision ID: 8841b895c05f
Revises: a3e46f5c6822
Create Date: 2025-06-11 19:02:18.349795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8841b895c05f'
down_revision = 'a3e46f5c6822'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produto_colecao',
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('colecao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['colecao_id'], ['colecoes.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], )
    )
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_column('colecao_2025')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('colecao_2025', sa.BOOLEAN(), nullable=True))

    op.drop_table('produto_colecao')
    # ### end Alembic commands ###
