"""Adiciona tabela de coleções e campo no produto

Revision ID: a3e46f5c6822
Revises: 511255eb93ca
Create Date: 2025-06-11 18:23:36.534183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3e46f5c6822'
down_revision = '511255eb93ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colecoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('imagem', sa.String(length=150), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_produtos_colecao_id',  # <- Adicione um nome único
            'colecoes',
            ['colecao_id'],
            ['id'],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('colecao_id')

    op.drop_table('colecoes')
    # ### end Alembic commands ###
