"""Adiciona cores_imagens no Produto

Revision ID: a5ccc77e3c5f
Revises: 4b455ee67653
Create Date: 2025-05-27 18:30:23.213278

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'a5ccc77e3c5f'
down_revision = '4b455ee67653'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cores_imagens', sqlite.JSON(), nullable=True))
        batch_op.drop_column('cores_disponiveis')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cores_disponiveis', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('cores_imagens')

    # ### end Alembic commands ###
