"""Adiciona cor e tipo_salto ao Produto

Revision ID: aa75bd1e34c2
Revises: db61639d4c41
Create Date: 2025-06-09 22:48:29.690867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa75bd1e34c2'
down_revision = 'db61639d4c41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cor', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tipo_salto', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_column('tipo_salto')
        batch_op.drop_column('cor')

    # ### end Alembic commands ###
