"""Adiciona campo peso com default

Revision ID: b283df9cfcce
Revises: 35cf43dc4a71
Create Date: 2025-05-27 11:14:51.962241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b283df9cfcce'
down_revision = '35cf43dc4a71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peso', sa.Float(), nullable=False, server_default='0.5'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_column('peso')

    # ### end Alembic commands ###
