"""Adiciona campos de frete ao Pedido

Revision ID: c892c37c1665
Revises: b283df9cfcce
Create Date: 2025-05-27 11:33:30.452811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c892c37c1665'
down_revision = 'b283df9cfcce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frete_valor', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('frete_transportadora', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('frete_prazo', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_column('frete_prazo')
        batch_op.drop_column('frete_transportadora')
        batch_op.drop_column('frete_valor')

    # ### end Alembic commands ###
