"""Adiciona tabela Banner

Revision ID: f894aa75d176
Revises: 393d4f95c726
Create Date: 2025-06-15 14:24:36.905002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f894aa75d176'
down_revision = '393d4f95c726'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=True),
    sa.Column('subtitulo', sa.String(length=200), nullable=True),
    sa.Column('imagem', sa.String(length=150), nullable=True),
    sa.Column('link_botao', sa.String(length=200), nullable=True),
    sa.Column('texto_botao', sa.String(length=50), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('banner')
    # ### end Alembic commands ###
